Document: foo
Title: Debian foo Manual
Author: <insert document author here>
Abstract: This manual describes what foo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/foo/foo.sgml.gz

Format: postscript
Files: /usr/share/doc/foo/foo.ps.gz

Format: text
Files: /usr/share/doc/foo/foo.text.gz

Format: HTML
Index: /usr/share/doc/foo/html/index.html
Files: /usr/share/doc/foo/html/*.html
